SELECT SUBSTR('MOVIE_DATABASE', 7) AS PROJECT FROM DUAL;
SELECT RPAD('MOVIEWORLD PRODUCTIONS',30, '.') AS RPAD FROM DUAL;
SELECT CHR(100) AS "ASCII" FROM DUAL;
SELECT 'Movie' || 'Project' AS Name FROM DUAL;

