-----------------------------------LEFT JOIN

SELECT E.EMPLOYEE_ID,E.NAME_,CR.DEPARTMENT_ID,CR.JOB_ID,CA.CAST_ID,CA.CHARACTER_
FROM EMPLOYEES E
LEFT JOIN CREW_CREDIT CR
ON (E.EMPLOYEE_ID=CR.EMPLOYEE_ID)
LEFT JOIN CAST_CREDIT CA
ON (CR.EMPLOYEE_ID=CA.EMPLOYEE_ID);
