SELECT  C.FILM_ID,m.name,D.DEPARTMENT_NAME,E.NAME_,J.JOB FROM crew_credýt C LEFT JOIN MOVIE M ON C.FILM_ID=M.ID
LEFT JOIN DEPARTMENT D ON C.DEPARTMENT_ID=d.ýd LEFT JOIN employees E  ON C.EMPLOYEE_ID=e.ýd 
LEFT JOIN JOBS J ON C.JOB_ID=J.ID
INTERSECT
SELECT C.FILM_ID,m.name,D.DEPARTMENT_NAME,E.NAME_,J.JOB FROM MOVIE M  LEFT JOIN CREW_CREDIT C ON C.FILM_ID=M.ID 
LEFT JOIN DEPARTMENT D ON C.DEPARTMENT_ID=D.ID LEFT JOIN EMPLOYEES E  ON C.EMPLOYEE_ID=E.ID 
LEFT JOIN JOBS J ON C.JOB_ID=J.ID
