declare 
ORTALAMA_HASILAT NUMBER := &REVENUE;
BEGIN
IF ORTALAMA_HASILAT > 168971979 THEN
    DBMS_OUTPUT.PUT_LINE('YUKSEK HASILATLI FILM');
ELSIF ORTALAMA_HASILAT = 168971979 THEN
    DBMS_OUTPUT.PUT_LINE('ORTALAMA HASILAT YAPAN FILM');
ELSE 
    DBMS_OUTPUT.PUT_LINE('DUSUK HASILATL YAPAN FILM');
END IF;
END;

