CREATE OR REPLACE VIEW VW_FILM_SECME
AS 
SELECT 
M.NAME,g.genre_name,r.content,R.AUTHOR,
EXTRACT(YEAR FROM m.release_date) AS YIL,
EXTRACT(MONTH FROM M.RELEASE_DATE) AS AY,
CASE
WHEN M.SPOKEN_LANGUAGE_CODE='en' THEN 'YERLÝ'
WHEN M.SPOKEN_LANGUAGE_CODE!='en' THEN 'YABANCI'
END AS KATEGORÝ
FROM   MOVIE M
INNER JOIN REVIEW R ON r.fýlm_ýd=m.ýd
INNER JOIN GENRES G ON m.genre_ýd=g.ýd;
select * from vw_fýlm_secme

