CREATE OR REPLACE VIEW ULKELERIN_URETTIGI_FILM_SAYISI
AS
	SELECT M.COUNTRY_CODE AS ULKEKODU,C.COUNTRY_NAME AS ULKENAME,
		COUNT(M.FILM_ID) AS FILMSAYISI
	FROM MOVIE M 
	INNER JOIN COUNTRIES C ON M.COUNTRY_CODE = C.CODE
	GROUP BY M.COUNTRY_CODE,C.COUNTRY_NAME
        ORDER BY 3 DESC;
        