CREATE or replace VIEW MOST_WATCHED_FILMS_BY_CATEGORY
AS
SELECT gn.genre_ýd,gn.genre_name,CAST(MV.RN AS VARCHAR2(30))|| '.' ||mv.name as FILM_NAME,mv.popularýty 
FROM GENRES GN
CROSS APPLY
(
SELECT ROW_NUMBER() OVER (ORDER BY M.POPULARITY DESC) RN,
M.NAME,M.FILM_ID,m.popularýty,G.GENRE_ID,G.GENRE_NAME FROM GENRES G
INNER JOIN MOVIE M  ON g.GENRE_ID = m.GENRE_ID
WHERE G.GENRE_ID = GN.GENRE_ID
AND POPULARITY IS NOT NULL
FETCH NEXT 5 ROWS ONLY
)MV;

SELECT * FROM MOST_WATCHED_FILMS_BY_CATEGORY;
