CREATE TABLE CAST_CREDIT(
ID NUMBER PRIMARY KEY ,
CAST_ID NUMBER,
FILM_ID NUMBER,
EMPLOYEE_ID NUMBER,
CREDIT_ID VARCHAR2(50),
CHARACTER_ VARCHAR2(500),
NAME_ VARCHAR2(500),
GENDER_ID NUMBER,
ORDERS NUMBER,
    CONSTRAINT FK_FILM_4 FOREIGN KEY(FILM_ID) REFERENCES MOVIE(ID),
    CONSTRAINT FK_EMPLOYEE_2 FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
    CONSTRAINT FK_CREDIT FOREIGN KEY(CREDIT_ID) REFERENCES CREW_CREDIT(CREDIT_ID),
    CONSTRAINT FK_GENDER_2 FOREIGN KEY(GENDER_ID) REFERENCES GENDER(ID)
);
