CREATE TABLE CREW_CREDIT
(
ID NUMBER ,
CREDIT_ID VARCHAR2(50) PRIMARY KEY,
FILM_ID NUMBER,
DEPARTMENT_ID NUMBER,
EMPLOYEE_ID NUMBER,
JOB_ID NUMBER,
NAME VARCHAR2(200),
    CONSTRAINT FK_FILM_3 FOREIGN KEY(FILM_ID) REFERENCES MOVIE(ID),
    CONSTRAINT FK_DEPARTMENT_2 FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
    CONSTRAINT FK_JOB FOREIGN KEY(JOB_ID) REFERENCES JOBS(ID)
);