
CREATE TABLE EMPLOYEES
(
ID NUMBER PRIMARY KEY,
EMPLOYEE_ID NUMBER,
NAME_ VARCHAR2(500),
DEPARTMENT_ID NUMBER,
BIRTHDAY DATE,
GENDER_ID NUMBER,
    CONSTRAINT FK_DEPARTMENT_1 FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
    CONSTRAINT FK_GENDER FOREIGN KEY(GENDER_ID) REFERENCES GENDER(ID)
);