CREATE TABLE JOBS(
ID NUMBER PRIMARY KEY,
DEPARTMENT_ID NUMBER,
DEPARTMENT_NAME VARCHAR2(200),
JOB VARCHAR2(500),
    CONSTRAINT FK_DEPARTMENT FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);