
CREATE TABLE MOVIE(
ID NUMBER PRIMARY KEY,
FILM_ID NUMBER,
NAME VARCHAR2(1000),
IMDB_ID VARCHAR2(1000),
ORIGINAL_LANGUAGE VARCHAR(500),
POPULARITY FLOAT,
RELEASE_DATE DATE,
TIME NUMBER,
VOTE_AVERAGE FLOAT,
VOTE_COUNT NUMBER,
COMPANY_ID NUMBER,
COUNTRY_CODE varchar2(10),
GENRE_ID NUMBER,
SPOKEN_LANGUAGE_CODE varchar2(10),
REVENUE NUMBER,
BUDGET NUMBER,
    CONSTRAINT FK_COMPANY FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(ID),
    CONSTRAINT FK_COUNTRY FOREIGN KEY(COUNTRY_CODE) REFERENCES COUNTRIES(CODE),
    CONSTRAINT FK_GENRE FOREIGN KEY(GENRE_ID) REFERENCES GENRES(GENRE_ID),
    CONSTRAINT FK_SPOKEN_LANGUAGE FOREIGN KEY(SPOKEN_LANGUAGE_CODE) REFERENCES SPOKEN_LANGUAGES(CODE)
);
